version: '3.8'
services:
    master_db:
        container_name: master_db
        image: postgres:15.2-alpine3.17
        restart: always
        command: postgres -c 'config_file=/etc/postgresql/postgresql.conf' -c 'hba_file=/etc/postgresql/pg_hba.conf'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/data
        ports:
            - '5438:5432'
        volumes:
            - master_db_vol:/data
            - ./master_conf/pg_hba.conf:/etc/postgresql/pg_hba.conf
            - ./master_conf/postgresql.conf:/etc/postgresql/postgresql.conf
            - ./master_conf/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - postgres-network
    slave_db:
        container_name: slave_db
        image: postgres:15.2-alpine3.17
        restart: always
        command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/data
        ports:
            - '5439:5432'
        volumes:
            - slave_db_vol:/data
            - ./slave_conf/postgresql.conf:/etc/postgresql/postgresql.conf
            - ./slave_conf/init.sh:/docker-entrypoint-initdb.d/init.sh
        networks:
            - postgres-network
        depends_on:
            - master_db
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - "8080:80"
        networks:
            - postgres-network
volumes:
    master_db_vol:
        driver: local
    slave_db_vol:
        driver: local
networks:
  postgres-network:
    driver: bridge
